services:
  postgres:
    image: postgres:16-alpine
    container_name: eventpass-postgres
    environment:
      POSTGRES_USER: eventpass
      POSTGRES_PASSWORD: eventpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
